name: tennis_game_example
description: A [Tennis kata](http://www.codingdojo.org/cgi-bin/index.pl?KataTennis) example.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

dev_dependencies:
  sealed_unions:
    path: ../
  test: ^1.16.8